### PR TITLE
Correct service switching

### LINKED ISSUE #11: Duration is not selected on service switch
### Problem
When switching services, new duration is not selected.

### Steps to reproduce
- Go to page with wizard components.
- Select service.
- Switch service to another one. New duration is not selected.

### Cause
Watcher is not fired, because value is set.

### Possible solution
Reimplement watcher to work in this scenario (when services can be switched).

### PR DESCRIPTION
**Pull request by romalytvynenko**
fixes #11

### CODE REVIEW

File: src/components/CfSessionDatePicker.js [hunk 1]
```diff
@@ -119,6 +106,15 @@ export default function (CreateDatetimeCapable, dateFormats) {
         }
       },
 
+      /**
+       * @since [*next-version*]
+       *
+       * @property {Date} openedMonth Month, on which datepicker is opened.
+       */
+      openedMonth: {
```
Comment (XedinUnknown) [inline src/components/CfSessionDatePicker.js]: Why did date change to month? The former sounds to be more flexible and accurate.

File: src/components/CfServiceSessionSelector.js [hunk 2]
```diff
@@ -339,7 +348,7 @@ export default function CfServiceSessionSelector (CreateDatetimeCapable, session
 
         this.$nextTick(() => {
           if (this.service) {
-            this.loadSessions(this.createLocalDatetime().toDate())
+            this.loadSessions(this.openedOnDate || this.createLocalDatetime().toDate())
```
Comment (XedinUnknown) [inline src/components/CfServiceSessionSelector.js]: `loadSessions()` accepts a parameter called `month` in the form of a `Date` instance. can you explain this please?

Comment (romalytvynenko) [reply src/components/CfServiceSessionSelector.js]: This will pass `this.createLocalDatetime().toDate()` to `loadSessions`, if `this.openedOnDate` is `null`.

Comment (XedinUnknown) [reply src/components/CfServiceSessionSelector.js]: Yes, I know that. The question was different.

File: src/components/CfServiceSessionSelector.js [hunk 3]
```diff
@@ -369,18 +378,18 @@ export default function CfServiceSessionSelector (CreateDatetimeCapable, session
        *
        * @since [*next-version*]
        *
-       * @param {Date} month Month for which sessions should be loaded.
+       * @param {Date} date Date for which sessions should be loaded.
```
Comment (XedinUnknown) [inline src/components/CfServiceSessionSelector.js]: This and similar occurrences should read something like "Date *in the range* for which sessions should be loaded", i.e. clearly indicating that the sessions will be loaded for the range, not just for the date.

File: src/components/CfServiceSessionSelector.js [hunk 4]
```diff
@@ -369,18 +378,18 @@ export default function CfServiceSessionSelector (CreateDatetimeCapable, session
...
        *
        * @return {{service: Number, start: (string), end: (string)}}
        */
-      _prepareSessionRequestParams (month) {
+      _prepareSessionRequestParams (date) {
         const currentDay = this.createLocalDatetime()
 
-        const firstDayOfMonth = this.createLocalDatetime(month).startOf('month')
-        const lastDayOfMonth = this.createLocalDatetime(month).endOf('month')
+        const firstDayOfRange = this.createLocalDatetime(date).startOf('month')
```
Comment (XedinUnknown) [inline src/components/CfServiceSessionSelector.js]: Abstract the range calculation, such that it only happens in one single place. This will give us the opportunity to easily understand the logic, and to change the range, for example to two weeks, or 3 months at a time.
